#!/usr/bin/env python3
"""
Interactive script to setup Supabase configuration for Akitoi.

This script will guide you through getting the necessary credentials
from Supabase and create a properly configured .env file.
"""
import os
import sys
from pathlib import Path
import secrets


def print_header(text):
    """Print a formatted header."""
    print("\n" + "=" * 60)
    print(f"  {text}")
    print("=" * 60 + "\n")


def print_step(number, text):
    """Print a step number."""
    print(f"\n{'=' * 60}")
    print(f"  PASO {number}: {text}")
    print('=' * 60)


def print_instructions(lines):
    """Print formatted instructions."""
    for line in lines:
        print(f"  {line}")
    print()


def get_input(prompt, default=None):
    """Get user input with optional default value."""
    if default:
        user_input = input(f"{prompt} [{default}]: ").strip()
        return user_input if user_input else default
    else:
        user_input = input(f"{prompt}: ").strip()
        while not user_input:
            print("  ⚠️  Este campo es requerido. Por favor ingresa un valor.")
            user_input = input(f"{prompt}: ").strip()
        return user_input


def main():
    """Main setup function."""
    print_header("🚀 Akitoi - Configuración de Supabase")

    print("Este script te ayudará a configurar Supabase para tu proyecto Akitoi.")
    print("Necesitarás tener tu proyecto de Supabase abierto en el browser.")
    print()

    input("Presiona ENTER para continuar...")

    # Step 1: Get Project Reference
    print_step(1, "Obtener Project Reference")
    print_instructions([
        "1. Abre tu proyecto en https://app.supabase.com",
        "2. Ve a 'Project Settings' (⚙️ en el menú lateral izquierdo)",
        "3. En la sección 'General', busca 'Reference ID'",
        "4. Copia el Reference ID (ejemplo: abcdefghijklm)"
    ])

    project_id = get_input("📝 Ingresa tu Project Reference ID")

    # Step 2: Get Database Password
    print_step(2, "Obtener Database Password")
    print_instructions([
        "⚠️  IMPORTANTE: Necesitas la contraseña de la base de datos.",
        "",
        "Si NO la recuerdas:",
        "1. Ve a 'Project Settings' > 'Database'",
        "2. Scroll hasta 'Connection string'",
        "3. Click en 'Reset database password'",
        "4. Genera una nueva contraseña SEGURA",
        "5. GUÁRDALA en un lugar seguro (la necesitarás después)",
        "",
        "Si SÍ la recuerdas, continúa."
    ])

    db_password = get_input("🔒 Ingresa tu Database Password")

    # Step 3: Get API Keys
    print_step(3, "Obtener API Keys")
    print_instructions([
        "1. En 'Project Settings', ve a la sección 'API'",
        "2. Busca 'Project API keys'",
        "3. Verás dos keys: 'anon public' y 'service_role'"
    ])

    print("\n📋 Copiando anon (public) key:")
    anon_key = get_input("  Pega aquí tu 'anon public' key")

    print("\n📋 Copiando service_role key:")
    service_role_key = get_input("  Pega aquí tu 'service_role' key")

    # Step 4: Generate SECRET_KEY
    print_step(4, "Generar Secret Key")
    print_instructions([
        "Generando una SECRET_KEY segura para tu aplicación..."
    ])

    secret_key = secrets.token_urlsafe(32)
    print(f"  ✅ SECRET_KEY generada: {secret_key[:20]}...")

    # Build configuration
    print_step(5, "Crear archivo .env")

    supabase_url = f"https://{project_id}.supabase.co"
    database_url = f"postgresql://postgres:{db_password}@db.{project_id}.supabase.co:5432/postgres"

    env_content = f"""# ============================================
# Supabase Database Configuration
# ============================================
# Generated by setup_supabase.py on {Path(__file__).name}
SUPABASE_URL={supabase_url}
SUPABASE_ANON_KEY={anon_key}
SUPABASE_SERVICE_ROLE_KEY={service_role_key}

# Direct database connection (for Alembic migrations)
DATABASE_URL={database_url}

# ============================================
# API Configuration
# ============================================
API_HOST=0.0.0.0
API_PORT=8000

# Environment
ENVIRONMENT=development

# CORS (comma-separated origins)
ALLOWED_ORIGINS=http://localhost:3000,http://localhost:5173

# ============================================
# Security
# ============================================
SECRET_KEY={secret_key}

# ============================================
# Optional: Local PostgreSQL (for development without Supabase)
# ============================================
# DATABASE_URL=postgresql://postgres:postgres@localhost:5432/akitoi
"""

    # Check if .env exists
    env_file = Path(__file__).parent.parent / '.env'

    if env_file.exists():
        print("  ⚠️  El archivo .env ya existe.")
        backup = input("  ¿Deseas hacer un backup antes de sobrescribir? (s/N): ").strip().lower()

        if backup in ['s', 'si', 'sí', 'yes', 'y']:
            backup_file = env_file.with_suffix('.env.backup')
            backup_file.write_text(env_file.read_text())
            print(f"  ✅ Backup creado: {backup_file}")

    # Write .env file
    env_file.write_text(env_content)
    print(f"  ✅ Archivo .env creado en: {env_file}")

    # Summary
    print_header("✅ Configuración Completada")
    print("Tu archivo .env ha sido creado con la siguiente configuración:\n")
    print(f"  Project ID:      {project_id}")
    print(f"  Supabase URL:    {supabase_url}")
    print(f"  Database URL:    postgresql://postgres:****@db.{project_id}.supabase.co:5432/postgres")
    print(f"  Anon Key:        {anon_key[:20]}...")
    print(f"  Service Role:    {service_role_key[:20]}...")
    print(f"  Secret Key:      {secret_key[:20]}...")

    # Next steps
    print_header("🎯 Próximos Pasos")
    print("1. Verificar la configuración:")
    print("   python3 -c \"from dotenv import load_dotenv; import os; load_dotenv(); print('DATABASE_URL configurado:', 'DATABASE_URL' in os.environ)\"")
    print()
    print("2. Inicializar la base de datos:")
    print("   ./scripts/init_db.sh")
    print()
    print("3. Verificar que todo esté correcto:")
    print("   python3 scripts/check_db.py")
    print()
    print("4. Ejecutar la API:")
    print("   ./scripts/run_dev.sh")
    print()
    print("=" * 60)

    # Test connection
    print("\n¿Deseas probar la conexión a la base de datos ahora? (S/n): ", end="")
    test = input().strip().lower()

    if test not in ['n', 'no']:
        print("\n🔌 Probando conexión a Supabase...")
        try:
            from sqlalchemy import create_engine, text

            test_url = database_url
            if test_url.startswith('postgres://'):
                test_url = test_url.replace('postgres://', 'postgresql://', 1)

            engine = create_engine(test_url)
            with engine.connect() as conn:
                result = conn.execute(text('SELECT version()'))
                version = result.scalar()
                print('✅ Conexión exitosa!')
                print(f'📊 PostgreSQL version: {version.split(",")[0]}')
        except Exception as e:
            print(f'❌ Error de conexión: {e}')
            print('\nVerifica:')
            print('  - Que el Project Reference ID sea correcto')
            print('  - Que la contraseña de la base de datos sea correcta')
            print('  - Que tu IP no esté bloqueada en Supabase')

    print("\n🎉 ¡Configuración completada!\n")


if __name__ == '__main__':
    try:
        main()
    except KeyboardInterrupt:
        print("\n\n❌ Configuración cancelada por el usuario.")
        sys.exit(1)
    except Exception as e:
        print(f"\n\n❌ Error inesperado: {e}")
        sys.exit(1)
