/**
 * Minimal Supabase Auth client (REST, no SDK).
 *
 * The backend only needs the access token (JWT) in Authorization; we
 * talk to Supabase's GoTrue REST API directly for login. When the env
 * vars are absent (local demo without a Supabase project), the login
 * view falls back to pasting a dev token generated by
 * scripts/make_demo_token.py.
 */

const SUPABASE_URL = process.env.NEXT_PUBLIC_SUPABASE_URL || ''
const SUPABASE_ANON_KEY = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY || ''

export const supabaseConfigured = Boolean(SUPABASE_URL && SUPABASE_ANON_KEY)

const TOKEN_KEY = 'akitoi_admin_token'

export function storedToken(): string | null {
  if (typeof window === 'undefined') return null
  return window.localStorage.getItem(TOKEN_KEY)
}

export function storeToken(token: string): void {
  window.localStorage.setItem(TOKEN_KEY, token)
}

export function clearToken(): void {
  window.localStorage.removeItem(TOKEN_KEY)
}

/** Token delivered by a Supabase magic-link redirect (#access_token=...). */
export function tokenFromUrlHash(): string | null {
  if (typeof window === 'undefined') return null
  const match = window.location.hash.match(/access_token=([^&]+)/)
  return match ? decodeURIComponent(match[1]) : null
}

/** Email + password sign-in. Returns the access token. */
export async function signInWithPassword(
  email: string,
  password: string
): Promise<string> {
  const response = await fetch(
    `${SUPABASE_URL}/auth/v1/token?grant_type=password`,
    {
      method: 'POST',
      headers: {
        apikey: SUPABASE_ANON_KEY,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({ email, password }),
    }
  )
  const body = await response.json()
  if (!response.ok || !body.access_token) {
    throw new Error(body.error_description || body.msg || 'Login fallido')
  }
  return body.access_token as string
}

/** Send a magic link; the redirect lands back with #access_token=... */
export async function sendMagicLink(email: string): Promise<void> {
  const response = await fetch(`${SUPABASE_URL}/auth/v1/otp`, {
    method: 'POST',
    headers: {
      apikey: SUPABASE_ANON_KEY,
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({
      email,
      create_user: true,
      options: { email_redirect_to: window.location.href },
    }),
  })
  if (!response.ok) {
    const body = await response.json().catch(() => ({}))
    throw new Error(body.error_description || body.msg || 'No se pudo enviar')
  }
}
